[tool.poetry]
name = "django-bootstrap-v5"
version = "1.0.11"
description = "Bootstrap 5 support for Django projects"
homepage = "https://github.com/zelenij/django-bootstrap-v5"
repository = "https://github.com/zelenij/django-bootstrap-v5"
documentation = "https://django-bootstrap-v5.readthedocs.io/"
authors = ["Andre Bar'yudin <andre.baryudin@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.md"
keywords= ["django", "django-bootstrap-v5", "bootstrap5", "bootstrap"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django :: 2.2",
    "Framework :: Django :: 3.0",
    "Framework :: Django",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
]
packages = [
    { include = "bootstrap5", from = "src" },
    { include = "docs", format = "sdist" },
    { include = "tests", format = "sdist" },
]
include = ["LICENSE"]

[tool.poetry.dependencies]
python = "^3.6"
django = "^2.2 || ^3.0 || ^4.0 || ^5.0" 
beautifulsoup4 = "^4.8.0"

# docs
sphinx = { version = "^4.4", optional = true }
sphinx_rtd_theme = { version = "^1.0", optional = true }
m2r2 = { version = "^0.2.5", optional = true }

[tool.poetry.dev-dependencies]
black = {version = "^20.8b1", allow-prereleases = true}
isort = "^5.6.3"
autoflake = "^1.4"
flake8 = "^3.8.4"
docformatter = "^1.3.1"
pydocstyle = "^5.1.1"
coverage = {extras = ["toml"], version = "^5.0.4"}
tox = "^3.20.1"

[tool.poetry.extras]
docs = ["sphinx", "sphinx_rtd_theme", "m2r2"]

[tool.black]
line-length = 120
target-version = ["py36"]

[tool.coverage.run]
branch = true
source = ["bootstrap5"]

[tool.coverage.paths]
source = ["src", ".tox/*/site-packages"]

[tool.coverage.report]
show_missing = true
skip_covered = true

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
